application: helloworld
version: 1
runtime: python
api_version: 1

inbound_services:
- xmpp_message

handlers:

- url: /(.*\.css)
  static_files: css/\1
  upload: css/(.*\.css)

- url: /.*
  script: app.py
